### PR TITLE
Performance enhancements (fixes #31)

### LINKED ISSUE #31: Reallocations causing huge memory demand
Reallocations of the state matrix happen at each
```
const dyn_mat<typename Derived1::Scalar>& rstate = state;
```
line in `operations.h` and each default copy thereof. I suspect this is because the reference is upcasted when passed as `const Eigen::MatrixBase<Derived1>& state` in the function argument and then needs to be converted back to a `dyn_mat`. For example, calling
```
psi = qpp::apply(psi, qpp::gt.X, {1});
```
from my code, a total of *nine* copies of the state are created within `operations.h`:

1. at line 578 (`apply` overload with `idx d`)

2. at line 492 (`apply` overload with `dims`)

3. at line 61 (`applyCTRL`)

4. for a copy reference in `coeff_idx_ket` (the copy constructor of `Matrix` is demonstrably called at the moment the `coeff_idx_ket` is defined) – is there a reason for it to be `[=]` anyway?

5. at line 358 (`result = rstate`),

along with temporary copies for the purposes of `internal::_check_cvector` and `internal::_check_dims_match_cvect` (at lines 532, 535, 349, 352). (Line numbers referring to  f0765d7baf04e13f69f5b55e6219d3cec4a7ed8d.) Obviously only number 5 is necessary.

This is no problem for small state vectors or density matrices but when the data reaches 1 GB it becomes a real issue.

### PR DESCRIPTION
**Pull request by vasekp**
**NB:** I'm very new to Eigen. Please confirm everything works as intended before merging.

I have checked this against the programs in `examples/`, except `input_output` as I don't have MATLAB. `channels` won't compile but I believe this is independent of my changes as I can recreate the same issue in a fresh clone.

### CODE REVIEW

**Comment by vsoftco** [comment]
Thanks for the modifications, I'll double check them then merge. I glanced over, everything should be OK. Regarding `channels.cpp`, it should compile. I just downloaded the latest version and doubled checked, and it compiles on my side (changed the line in `CMakeLists.txt` with `examples/channels.cpp`). Can you double check that? And if it still doesn't compile, can you please let me know how you compile it, plus gcc/clang version?

**Comment by vasekp** [comment]
It's missing `begin()` and `end()` in `VectorXcd`, specifically in `channels.cpp:27` where `sum(hevals(...))` is requested while `hevals()` returns a `dyn_col_vect<double>` (`functions.h:391`). I thought they never were there ([1], [2]). I'm using g++ 6.1.1 20160621 and latest `hg` changeset of Eigen, `3b011bdf6a7e`. Maybe I'm having some typo in the compile command as I also recall having compiled that with no problem earlier. But it's taken straight out of `README.md`.

Here's my command:
```
g++ -pedantic -std=c++11 -Wall -Wextra -Weffc++ -fopenmp -O3 -DNDEBUG -DEIGEN_NO_DEBUG -isystem $HOME/prog/src/eigen -I ../include channels.cpp -o channels
```
and the main error message:
```
../include/functions.h:1716:26: error: no matching function for call to ‘begin(const Eigen::Matrix<double, -1, 1>&)’
     return sum(std::begin(c), std::end(c));
```

[1]: http://eigen.tuxfamily.org/bz/show_bug.cgi?id=231
[2]: http://stackoverflow.com/questions/26291861/use-stdbegin-stdend-to-convert-arrayxd-to-stl-vector

**Comment by vasekp** [comment]
Edit: it does compile with the "latest stable release" from http://eigen.tuxfamily.org/index.php?title=Main_Page. I wonder if the support for STL iterators was actually *removed* between that and the bleeding-edge version (the latest commit in my `hg` clone was yesterday!)

**Comment by vsoftco** [comment]
I believe the issue is with the selected overload. In the stable version, I think the `qpp::sum(const Eigen::MatrixBase<Derived>& A)` is being selected, which works fine. However in the Eigen dev version it seems that the general overload `qpp::sum(const Container& c)` is selected, which invokes `std::begin`, which of course doesn't work. I'll play around with it and see what exactly happens, then finally merge everything. Thanks a lot for taking the time!

**Pull request merged**
